languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Tales Casagrande"
description = "Cloud Security | Human | Father"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params.author]
  name = "Tales Casagrande a.k.a Taleco"
  image = "img/author.jpg"
  headline = "IT Security | Human | Father | Coffee "
  bio = "Cloud Security | Human | Father"
  links = [
    { x-twitter = "https://twitter.com/100HnoMeuNome", github = "https://github.com/100HnoMeuNome", instagram = "https://www.instagram.com/tempthebunny/", linkedin = "https://www.linkedin.com/in/talescasagrande/", medium = "https://medium.com/@100HnoMeuNome", twitch = "https://www.twitch.tv/tiosdowarzone", youtube = "https://www.youtube.com/@100hnomeunome", spotify = "https://open.spotify.com/playlist/3T4t8IF7joe466LQIKnsYc?si=5ae0f76517564839", tiktok = "https://www.tiktok.com/@tiosdowarzone", email = "tales.775@gmail.com"}
    
]
