# config/_default/menus.en.toml

[[main]]
  name = "Talk Sessions"
  pageRef = "talk-sessions"
  weight = 10

[[main]]
  name = "Articles"
  pageRef = "articles"
  weight = 10

[[main]]
  name = "Podcast"
  pageRef = "podcast"
  weight = 10

[[main]]
  name = "My Favorite"
  pageRef = "my-Favorite"
  weight = 10

[[main]]
  name = "Community Projects"
  pageRef = "community-projects"
  weight = 10

[[main]]
  name = "Buy Me a Coffee"
  pageRef = "buy-me-a-coffee"
  weight = 10
