# config/_default/menus.en.toml

[[main]]
  name = "Talk Sessions"
  pageRef = "talk-sessions"
  weight = 10

[[main]]
  name = "Articles"
  pageRef = "articles"
  weight = 10

[[main]]
  name = "Podcast"
  pageRef = "podcast"
  weight = 10

[[main]]
  name = "My Favorite"
  pageRef = "my-favorite"
  weight = 10

[[main]]
  name = "Community Projects"
  pageRef = "community"
  weight = 10

[[main]]
  name = "Buy Me a Coffee"
  pageRef = "BuyMeaCoffee"
  weight = 10
